---

###
### Lints all generic and json files in the whole git repository
###

name: fuzzing
on:
  pull_request:
  push:
    branches:
      - master
    tags:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        version:
          - '2.7'
          - '3.6'
          - '3.7'
          - '3.8'

    name: "[ ${{ matrix.target }} ${{ matrix.version}} ]"
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.version }}
          architecture: x64

      - name: Fuzzing - before install
        run: |
          .ci/fuzzy.sh

      - name: Fuzzing - after install
        run: |
          sudo make install
          .ci/fuzzy.sh
